version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    cooldown:
      default-days: 7
    directories:
      - /terraform/bootstrap
      - /terraform/scanner
      - /terraform/org-roles
    schedule:
      interval: monthly
